name: Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Run after job1
        run: echo "Job2 is running because Job1 finished successfully""
